// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaMCH9LosfC0HDPI9PD1igNZ7UABibSEU',
    appId: '1:856802262712:web:92325b4a20d2483a943e4d',
    messagingSenderId: '856802262712',
    projectId: 'pushnotification-ca8f7',
    authDomain: 'pushnotification-ca8f7.firebaseapp.com',
    storageBucket: 'pushnotification-ca8f7.firebasestorage.app',
    measurementId: 'G-2TH9TVJ235',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_SasWjYKp6T-4vWz9WVD4stcH3GQQ0Mw',
    appId: '1:856802262712:android:93dc2d85d400dc35943e4d',
    messagingSenderId: '856802262712',
    projectId: 'pushnotification-ca8f7',
    storageBucket: 'pushnotification-ca8f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhFWIcazFdo5k_lXgQ0djH2ZZgZ_37wd0',
    appId: '1:856802262712:ios:fe81b5290b9388c8943e4d',
    messagingSenderId: '856802262712',
    projectId: 'pushnotification-ca8f7',
    storageBucket: 'pushnotification-ca8f7.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhFWIcazFdo5k_lXgQ0djH2ZZgZ_37wd0',
    appId: '1:856802262712:ios:fe81b5290b9388c8943e4d',
    messagingSenderId: '856802262712',
    projectId: 'pushnotification-ca8f7',
    storageBucket: 'pushnotification-ca8f7.firebasestorage.app',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaMCH9LosfC0HDPI9PD1igNZ7UABibSEU',
    appId: '1:856802262712:web:c96bc43bbbaceac7943e4d',
    messagingSenderId: '856802262712',
    projectId: 'pushnotification-ca8f7',
    authDomain: 'pushnotification-ca8f7.firebaseapp.com',
    storageBucket: 'pushnotification-ca8f7.firebasestorage.app',
    measurementId: 'G-SFQ3MHR6KQ',
  );
}
